# Generated by Django 6.0.5 on 2026-05-31 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Serviceprofile',
        ),
    ]
