# Generated by Django 6.0.5 on 2026-06-18 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='count',
        ),
        migrations.AddField(
            model_name='review',
            name='likes_count',
            field=models.IntegerField(default=0),
        ),
    ]
